import { existsSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { colors, themes } from "../../colors.ts";
import { easings } from "../../easings.ts";
import { fonts } from "../../fonts.ts";
import { breakpoints, customSizes, layout, screens } from "../../layout.ts";
import { typography } from "../../typography.ts";
import { generateFontOverrides } from "../generate-font-overrides.ts";
import { generateFonts } from "../generate-fonts.ts";
import { generateMedia } from "../generate-media.ts";
import { generateRoot } from "../generate-root.ts";
import { generateScale } from "../generate-scale.ts";
import { generateTailwind } from "../generate-tailwind.ts";

interface DarkroomStylingOptions {
  prependCss?: string;
  watchFiles?: string[];
}

const defaults: Required<DarkroomStylingOptions> = {
  prependCss: "./styles/css/media.css",
  watchFiles: [
    "styles/colors.ts",
    "styles/typography.ts",
    "styles/easings.ts",
    "styles/layout.ts",
    "styles/fonts.ts",
  ],
};

const banner = `/*
 * THIS FILE IS GENERATED BY darkroom-styling vite plugin
 * DO NOT EDIT IT DIRECTLY.
 */`;

function generate() {
  // `BUILD_LANG` is set by `lib/static-i18n/build` for per-locale static
  // zips. When set, generateFonts emits only the matching language's
  // font file and generateFontOverrides is skipped (single-file build).
  const buildLang = process.env.BUILD_LANG;

  const tw = generateTailwind({
    breakpoints,
    colors,
    customSizes,
    easings,
    fonts,
    themes,
    typography,
  });
  const root = generateRoot({ colors, customSizes, easings, layout, screens });
  const scale = generateScale();
  const media = generateMedia({ breakpoints });
  const fontFaces = generateFonts({ fonts, buildLang });
  const fontOverrides = buildLang ? "" : generateFontOverrides({ fonts });

  writeFileSync("./styles/css/tailwind.css", [banner, tw, scale].join("\n\n"));
  writeFileSync(
    "./styles/css/root.css",
    [banner, root, fontOverrides].filter(Boolean).join("\n\n"),
  );
  writeFileSync("./styles/css/media.css", [banner, media].join("\n\n"));
  writeFileSync("./styles/css/fonts.css", [banner, fontFaces].join("\n\n"));

  console.log("✓ Style config generated");
}

export function darkroomStyling(options?: DarkroomStylingOptions): Plugin {
  const config = { ...defaults, ...options };
  const prependResolved = path.resolve(config.prependCss);

  return {
    name: "darkroom-styling",
    enforce: "pre",

    // Generate CSS files once before anything else
    configResolved() {
      generate();
    },

    // In dev: watch config files and regenerate on change
    configureServer(server) {
      server.watcher.add(config.watchFiles);
      server.watcher.on("change", (filePath) => {
        if (config.watchFiles.some((file) => filePath.includes(file))) {
          generate();
        }
      });
    },

    // Prepend @import for custom media queries into all CSS files
    transform(code, id) {
      if (!existsSync(prependResolved) || !id.endsWith(".css")) return;

      const parts = code.split("\n");
      let insertIndex = 0;

      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed.startsWith("@charset") || trimmed.startsWith("@layer")) {
          insertIndex++;
        } else {
          break;
        }
      }

      parts.splice(insertIndex, 0, `@import '${config.prependCss}';`);
      return parts.join("\n");
    },
  };
}
