import { existsSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import type { Plugin } from "vite";
import { generateFontOverrides } from "../generate-font-overrides.ts";
import { generateFonts } from "../generate-fonts.ts";
import { generateMedia } from "../generate-media.ts";
import { generateRoot } from "../generate-root.ts";
import { generateScale } from "../generate-scale.ts";
import { generateTailwind } from "../generate-tailwind.ts";

// Dynamic imports keep these out of Vite's config-dep graph, so editing
// them triggers in-place regen via the plugin's watcher instead of a
// full Vite server restart. The `?t=<timestamp>` query busts the module
// cache so each regen sees fresh values.
async function loadStyleConfig() {
  const t = Date.now();
  const url = (file: string) => `${new URL(`../../${file}`, import.meta.url).href}?t=${t}`;
  const [colorsMod, easingsMod, fontsMod, layoutMod, typographyMod] = await Promise.all([
    import(url("colors.ts")),
    import(url("easings.ts")),
    import(url("fonts.ts")),
    import(url("layout.ts")),
    import(url("typography.ts")),
  ]);
  return {
    colors: colorsMod.colors,
    themes: colorsMod.themes,
    easings: easingsMod.easings,
    fonts: fontsMod.fonts,
    breakpoints: layoutMod.breakpoints,
    customSizes: layoutMod.customSizes,
    layout: layoutMod.layout,
    screens: layoutMod.screens,
    typography: typographyMod.typography,
  };
}

interface DarkroomStylingOptions {
  prependCss?: string;
  watchFiles?: string[];
}

const defaults: Required<DarkroomStylingOptions> = {
  prependCss: "./styles/css/media.css",
  watchFiles: [
    "styles/colors.ts",
    "styles/fonts.ts",
    "styles/typography.ts",
    "styles/easings.ts",
    "styles/layout.ts",
  ],
};

const banner = `/*
 * THIS FILE IS GENERATED BY darkroom-styling vite plugin
 * DO NOT EDIT IT DIRECTLY.
 */`;

async function generate() {
  const { breakpoints, colors, customSizes, easings, fonts, layout, screens, themes, typography } =
    await loadStyleConfig();

  // `BUILD_LANG` is set by `lib/static-i18n/build` for per-locale static
  // zips. When set, generateFonts emits only the matching language's
  // font file and generateFontOverrides is skipped (single-file build).
  const buildLang = process.env.BUILD_LANG;

  const tw = generateTailwind({
    breakpoints,
    colors,
    customSizes,
    easings,
    fonts,
    themes,
    typography,
  });
  const root = generateRoot({ colors, customSizes, easings, layout, screens });
  const scale = generateScale();
  const media = generateMedia({ breakpoints });
  const fontFaces = generateFonts({ fonts, buildLang });
  const fontOverrides = buildLang ? "" : generateFontOverrides({ fonts });

  // Atomic writes: write to temp file then rename, so Vite's watcher
  // never observes a half-written CSS file.
  const writeAtomic = (file: string, contents: string) => {
    const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
    writeFileSync(tmp, contents);
    renameSync(tmp, file);
  };
  writeAtomic("./styles/css/tailwind.css", [banner, tw, scale].join("\n\n"));
  writeAtomic("./styles/css/root.css", [banner, root, fontOverrides].filter(Boolean).join("\n\n"));
  writeAtomic("./styles/css/media.css", [banner, media].join("\n\n"));
  writeAtomic("./styles/css/fonts.css", [banner, fontFaces].join("\n\n"));

  const time = new Date().toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
  console.log(`\x1b[2m${time}\x1b[0m \x1b[1m\x1b[31m[drkrm]\x1b[0m style config generated`);
}

// Shared across plugin instances (e.g. client + ssr environments) so
// concurrent change events collapse into a single regen.
let inFlight: Promise<void> | null = null;
function runGenerate() {
  if (inFlight) return inFlight;
  inFlight = generate().finally(() => {
    inFlight = null;
  });
  return inFlight;
}

export function darkroomStyling(options?: DarkroomStylingOptions): Plugin {
  const config = { ...defaults, ...options };
  const prependResolved = path.resolve(config.prependCss);

  return {
    name: "darkroom-styling",
    enforce: "pre",

    // Generate CSS files once before anything else
    async configResolved() {
      await runGenerate();
    },

    // In dev: watch config files and regenerate on change
    configureServer(server) {
      server.watcher.add(config.watchFiles);
      server.watcher.on("change", async (filePath) => {
        if (config.watchFiles.some((file) => filePath.includes(file))) {
          await runGenerate();
        }
      });
    },

    // Prepend @import for custom media queries into all CSS files
    transform(code, id) {
      if (!existsSync(prependResolved) || !id.endsWith(".css")) return;

      const parts = code.split("\n");
      let insertIndex = 0;

      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed.startsWith("@charset") || trimmed.startsWith("@layer")) {
          insertIndex++;
        } else {
          break;
        }
      }

      parts.splice(insertIndex, 0, `@import '${config.prependCss}';`);
      return parts.join("\n");
    },
  };
}
