import { existsSync, renameSync, writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { Plugin } from "vite";
import { generateFontOverrides } from "./generate-font-overrides.ts";
import { generateMedia } from "./generate-media.ts";
import { generateRoot } from "./generate-root.ts";
import { generateScale } from "./generate-scale.ts";
import { generateTailwind } from "./generate-tailwind.ts";

export interface DarkroomStylingOptions {
  /** Dir holding the token files (colors/easings/fonts/layout/typography.ts). Resolved against the project root. */
  configDir: string;
  /** Dir where tailwind.css / root.css / media.css are written. Resolved against the project root. */
  outDir: string;
  /** CSS `@import`-prepended into every stylesheet (custom-media defs). Default `<outDir>/media.css`. */
  prependCss?: string;
  /** Files whose changes trigger regeneration in dev. Default: the token files in `configDir`. */
  watchFiles?: string[];
}

/** Token files imported from `configDir`. The consuming app must provide these by name. */
const TOKEN_FILES = ["colors.ts", "easings.ts", "fonts.ts", "layout.ts", "typography.ts"] as const;

// Dynamic imports keep the token files out of Vite's config-dep graph, so editing
// them triggers in-place regen via the plugin's watcher instead of a full Vite
// server restart. The `?t=<timestamp>` query busts the module cache so each regen
// sees fresh values.
async function loadStyleConfig(configDir: string) {
  const t = Date.now();
  const url = (file: string) => `${pathToFileURL(path.join(configDir, file)).href}?t=${t}`;
  const [colorsMod, easingsMod, fontsMod, layoutMod, typographyMod] = await Promise.all([
    import(url("colors.ts")),
    import(url("easings.ts")),
    import(url("fonts.ts")),
    import(url("layout.ts")),
    import(url("typography.ts")),
  ]);
  return {
    colors: colorsMod.colors,
    themes: colorsMod.themes,
    easings: easingsMod.easings,
    fonts: fontsMod.fonts,
    breakpoints: layoutMod.breakpoints,
    customSizes: layoutMod.customSizes,
    layout: layoutMod.layout,
    screens: layoutMod.screens,
    typography: typographyMod.typography,
  };
}

const banner = `/*
 * THIS FILE IS GENERATED BY darkroom-styling vite plugin
 * DO NOT EDIT IT DIRECTLY.
 */`;

async function generate(configDir: string, outDir: string) {
  const { breakpoints, colors, customSizes, easings, fonts, layout, screens, themes, typography } =
    await loadStyleConfig(configDir);

  const tw = generateTailwind({
    breakpoints,
    colors,
    customSizes,
    easings,
    fonts,
    themes,
    typography,
  });
  const root = generateRoot({ colors, customSizes, easings, layout, screens });
  const scale = generateScale();
  const media = generateMedia({ breakpoints });
  const fontOverrides = generateFontOverrides({ fonts });

  // Atomic writes: write to temp file then rename, so Vite's watcher
  // never observes a half-written CSS file.
  const writeAtomic = (file: string, contents: string) => {
    const tmp = `${file}.${process.pid}.${Date.now()}.tmp`;
    writeFileSync(tmp, contents);
    renameSync(tmp, file);
  };
  writeAtomic(path.join(outDir, "tailwind.css"), [banner, tw, scale].join("\n\n"));
  writeAtomic(
    path.join(outDir, "root.css"),
    [banner, root, fontOverrides].filter(Boolean).join("\n\n"),
  );
  writeAtomic(path.join(outDir, "media.css"), [banner, media].join("\n\n"));

  const time = new Date().toLocaleTimeString("en-US", {
    hour: "numeric",
    minute: "2-digit",
    second: "2-digit",
    hour12: true,
  });
  console.log(`\x1b[2m${time}\x1b[0m \x1b[1m\x1b[31m[drkrm]\x1b[0m style config generated`);
}

// Shared across plugin instances (e.g. client + ssr environments) so
// concurrent change events collapse into a single regen.
let inFlight: Promise<void> | null = null;
function runGenerate(configDir: string, outDir: string) {
  if (inFlight) return inFlight;
  inFlight = generate(configDir, outDir).finally(() => {
    inFlight = null;
  });
  return inFlight;
}

export function darkroomStyling(options: DarkroomStylingOptions): Plugin {
  // Resolve here (against cwd = project root under Vite) so callers can pass
  // plain relative paths. `prependCss` is intentionally NOT resolved — it is
  // injected verbatim as a CSS `@import` specifier.
  const configDir = path.resolve(options.configDir);
  const outDir = path.resolve(options.outDir);
  const prependCss = options.prependCss ?? path.join(outDir, "media.css");
  const watchFiles = options.watchFiles ?? TOKEN_FILES.map((file) => path.join(configDir, file));
  const prependResolved = path.resolve(prependCss);

  return {
    name: "darkroom-styling",
    enforce: "pre",

    // Generate CSS files once before anything else
    async configResolved() {
      await runGenerate(configDir, outDir);
    },

    // In dev: watch config files and regenerate on change
    configureServer(server) {
      server.watcher.add(watchFiles);
      server.watcher.on("change", async (filePath) => {
        if (watchFiles.some((file) => filePath.includes(file))) {
          await runGenerate(configDir, outDir);
        }
      });
    },

    // Prepend @import for custom media queries into all CSS files.
    // Skip virtual modules (id starts with \0) — they have no filesystem
    // location so a relative @import would fail to resolve.
    transform(code, id) {
      if (!existsSync(prependResolved) || !id.endsWith(".css") || id.startsWith("\0")) return;

      const parts = code.split("\n");
      let insertIndex = 0;

      for (const part of parts) {
        const trimmed = part.trim();
        if (trimmed.startsWith("@charset") || trimmed.startsWith("@layer")) {
          insertIndex++;
        } else {
          break;
        }
      }

      parts.splice(insertIndex, 0, `@import '${prependCss}';`);
      return parts.join("\n");
    },
  };
}
