import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";
import type { Plugin } from "vite";
import { cacheKey, readCache, writeCache } from "./cache.ts";
import { PRESET_RANGES } from "./presets.ts";
import { clearRegistry, registerFont } from "./registry.ts";
import { subsetFont } from "./subset.ts";
import type {
  FontDefinition,
  FontSrc,
  ResolvedFontSrc,
  SubsetConfig,
} from "./types.ts";

export interface FontOptimizerOptions {
  fonts: FontDefinition[];
  /** Directory (relative to project root) where fonts.css and the subsetted woff2 files are written. */
  outDir?: string;
}

function resolveUnicodeRange(subset: SubsetConfig | undefined): string | null {
  if (!subset) return null;
  if (typeof subset === "string") return PRESET_RANGES[subset] ?? null;
  if ("unicodeRange" in subset) return subset.unicodeRange;
  const cps = [...new Set([...subset.chars])]
    .map((c) => c.codePointAt(0))
    .filter((cp): cp is number => cp !== undefined);
  return cps
    .map((cp) => `U+${cp.toString(16).toUpperCase().padStart(4, "0")}`)
    .join(", ");
}

function subsetSuffix(subset: SubsetConfig | undefined): string {
  if (!subset) return "";
  if (typeof subset === "string") return `-${subset}`;
  if ("unicodeRange" in subset) return "-custom";
  return "-chars";
}

function outputFilename(srcPath: string, subset: SubsetConfig | undefined): string {
  const stem = basename(srcPath).replace(/\.[^.]+$/, "");
  return `${stem}${subsetSuffix(subset)}.woff2`;
}

function fontFaceBlock(
  family: string,
  srcUrl: string,
  weight: string,
  style: string,
  display: string,
): string {
  return [
    "@font-face {",
    `  font-family: "${family}";`,
    `  src: url("${srcUrl}") format("woff2");`,
    `  font-weight: ${weight};`,
    `  font-style: ${style};`,
    `  font-display: ${display};`,
    "}",
  ].join("\n");
}

async function produceWoff2(
  srcRelPath: string,
  subset: SubsetConfig | undefined,
  fontsDirAbs: string,
  root: string,
): Promise<string> {
  const absSrc = resolve(root, srcRelPath);
  const sourceBytes = new Uint8Array(readFileSync(absSrc));

  const unicodeRange = resolveUnicodeRange(subset);
  if (!unicodeRange) {
    throw new Error(
      `font-optimizer: ${srcRelPath} has no subset config — passthrough not supported in v1`,
    );
  }

  const key = cacheKey(sourceBytes, unicodeRange);
  let bytes = readCache(key);
  if (!bytes) {
    bytes = await subsetFont(sourceBytes, unicodeRange);
    writeCache(key, bytes);
  }

  const filename = outputFilename(srcRelPath, subset);
  writeFileSync(join(fontsDirAbs, filename), bytes);
  return `./fonts/${filename}`;
}

export function fontOptimizer(options: FontOptimizerOptions): Plugin {
  const outDir = options.outDir ?? "styles/css";
  let resolvedRoot = process.cwd();

  return {
    name: "font-optimizer",
    enforce: "pre",

    configResolved(config) {
      resolvedRoot = config.root;
    },

    async buildStart() {
      clearRegistry();

      const outDirAbs = resolve(resolvedRoot, outDir);
      const fontsDirAbs = join(outDirAbs, "fonts");
      mkdirSync(fontsDirAbs, { recursive: true });

      const faces: string[] = [];

      for (const font of options.fonts) {
        if (typeof font.src === "string") {
          const url = await produceWoff2(font.src, font.subset, fontsDirAbs, resolvedRoot);
          registerFont({ ...font, resolvedUrl: url });
          if (font.css !== false) {
            faces.push(
              fontFaceBlock(
                font.family,
                url,
                font.weight ?? "400",
                "normal",
                font.display ?? "swap",
              ),
            );
          }
        } else {
          const resolvedSrcs: ResolvedFontSrc[] = [];
          for (const s of font.src as FontSrc[]) {
            const url = await produceWoff2(s.path, font.subset, fontsDirAbs, resolvedRoot);
            resolvedSrcs.push({ ...s, url });
            if (font.css !== false) {
              faces.push(
                fontFaceBlock(
                  font.family,
                  url,
                  s.weight,
                  s.style ?? "normal",
                  font.display ?? "swap",
                ),
              );
            }
          }
          registerFont({ ...font, resolvedUrl: resolvedSrcs });
        }
      }

      const banner = "/* GENERATED BY lib/font-optimizer — DO NOT EDIT */";
      writeFileSync(join(outDirAbs, "fonts.css"), `${banner}\n\n${faces.join("\n\n")}\n`);
    },
  };
}
